### ISSUE TITLE
list Index out of range

### ISSUE THREAD

**Issue by Cwavs** [rlaphoenix/pymplschapters#1]
On some MPLS files I'm getting a list Index out of range error, I'm not too sure why. I've attached the mpls files in question in case it helps but I'm not too sure what other relevant information there could be, so let me know if there's any more I can provide to help with debugging.

Command output:
```shell
Processing file...
Extracted chapters for 00000.m2ts
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\pymplschapters.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\pymplschapters\__init__.py", line 63, in main
    for file_with_chapter in get_chapters(playlist_handle):
  File "C:\Python310\lib\site-packages\pymplschapters\__init__.py", line 41, in get_chapters
    offset = playItemMarks[0]["MarkTimeStamp"]
IndexError: list index out of range
```

[MPLS Files](https://github.com/rlaphoenix/pymplschapters/files/10315535/PLAYLIST.zip)

**Comment by rlaphoenix** [comment]
Hi, I'd like to thank you for creating this issue.

It seems what's happening here is multiple of the play items (m2ts files) within these playlists do not actually have any chapters.
However, I would like to ask you if you could verify this by playing the Blu-ray through VLC or such and checking this.

Once I fixed up the code, this is the following result of `00087.mpls`:

```
Processing file...
Extracted chapters for 00000.m2ts
No chapters in Playlist for 00001.m2ts
Extracted chapters for 00002.m2ts
No chapters in Playlist for 00003.m2ts
No chapters in Playlist for 00004.m2ts
Extracted chapters for 00007.m2ts
Extracted chapters for 00078.m2ts
Extracted chapters for 00009.m2ts
No chapters in Playlist for 00079.m2ts
No chapters in Playlist for 00011.m2ts
Extracted chapters for 00080.m2ts
No chapters in Playlist for 00081.m2ts
Extracted chapters for 00016.m2ts
No chapters in Playlist for 00017.m2ts
Extracted chapters for 00082.m2ts
No chapters in Playlist for 00083.m2ts
No chapters in Playlist for 00020.m2ts
Extracted chapters for 00024.m2ts
No chapters in Playlist for 00025.m2ts
No chapters in Playlist for 00084.m2ts
No chapters in Playlist for 00085.m2ts
Extracted chapters for 00086.m2ts
Extracted chapters for 00087.m2ts
```

Therefore could you verify if those m2ts files really don't have any associated chapters? (when played back in VLC with Menu enabled)

My code matches Chapter information (playlist marks) with Play Items by matching by ID in a sort of assumed/unconfirmed way. Effectively each play item was given an assumed ID of their order in the MPLS. E.g., the first item (00000.m2ts) was given an id of 0, and the sixth item (00007.m2ts) was given an id of 5, and so on. It's possible this is an incorrect method of matching and I wouldn't be surprised.

I can't get access to any of the official documentation so we are out in the dark on this one unless we test.
As for testing to see if the m2ts's have chapters, I can only recommend opening in VLC and playing whatever that m2ts is (e.g., a menu, a short commercial/ad, piracy warning, e.t.c) and see if VLC shows chapters for it. You must play with the Blu-ray menu enabled.

I've pushed the code needed to skip the empty play items if you wanted the XML output for the ones that are matching, if that helps.

**Comment by Cwavs** [comment]
I'll play them in VLC to confirm, but a lack of chapters would make sense. The blu-ray this is from has two versions of the same episodes, one with updated SFX and one with the original model shots. Those playlists are for the different versions. I'd guess that some of the files are in between the episode's parts and likely wouldn't have chapters as a result.

**Comment by Cwavs** [comment]
I've played it back in VLC and I can confirm those files don't have chapters. This seems to have been the issue, so I'll close this now.
